src/blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blog import settings

urlpatterns = [
    path('jl_admin/', admin.site.urls),
    path('blog/', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path
from .import views
from django.contrib.auth.decorators import login_required

app_name = 'posts'
urlpatterns = [
    path('', views.BlogHome.as_view(), name='home'),
    path('create/', login_required(views.BlogPostCreate.as_view()), name='create'),
    path('post-<str:pk>/', views.BlogPostDetail.as_view(), name='show'),
    path('post-<str:pk>/update/', views.BlogPostUpdate.as_view(), name='update'),
    path('post-<str:pk>/delete/', views.BlogPostDelete.as_view(), name='delete'),
]

src/posts/models.py
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.db import models
from django.urls import reverse

User = get_user_model()


class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='Titre')
    slug = models.SlugField(max_length=255, unique=True, blank='Titre')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name='Publié')
    content = models.TextField(blank=True, verbose_name='Contenu')
    thumbnail = models.ImageField(blank=True, upload_to='blog')

    class Meta:
        ordering = ['-created_on']
        verbose_name = 'Article'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    @property
    def author_or_default(self):
        return self.author.username if self.author else 'un auteur inconnu'

    def get_absolute_url(self):
        return reverse('posts:home')

src/posts/forms.py
from django import forms
from .models import BlogPost


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = [
            'title',
            'content',
            'thumbnail',
        ]

src/posts/views.py
from django.urls import reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import BlogPost
from .forms import BlogPostForm


class BlogHome(ListView):
    model = BlogPost
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset

        return queryset.filter(published=True)


class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = 'posts/blogpost_create.html'
    form_class = BlogPostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['bouton'] = 'Créer'
        context['title'] = 'Ajouter un article'
        return context


class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = 'posts/blogpost_create.html'
    form_class = BlogPostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['bouton'] = 'Modifier'
        context['title'] = "Modifier l'article"
        return context


class BlogPostDetail(DetailView):
    model = BlogPost
    template_name = 'posts/show.html'
    context_object_name = 'post'


class BlogPostDelete(DeleteView):
    model = BlogPost
    template_name = 'posts/delete.html'
    context_object_name = 'post'

    def get_success_url(self):
        return reverse('posts:home')

src/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
    <title>Ajouter un article</title>
{% endblock %}

{% block content %}

<h1>{{title}}</h1>
<form method="POST">
    {% csrf_token %}

        {{form}}

        <input type="submit" value="{{bouton}}">


</form>

{% endblock %}

src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Accueil du blog</title>
{% endblock %}

{% block content %}

<h1>Le blog de Jean-Luc</h1>
{% for post in posts %}
    <article>
        <div class="post-title">
            <h2>{{post.title|upper}}</h2>
        </div>
        <h5 class="post-author">Publié par <i>{{post.author_or_default}}</i> le {{post.created_on}}</h5>
        <p class="post-excerpt">{{post.content|safe|truncatewords:20}}</p>
    </article>
    <div class="lien">
        <form action="{% url 'posts:show' pk=post.id %}">
            <button class="btn btn-submit">Lire la suite</button>
        </form>
    </div>
{% if not forloop.last %}
<hr class="ligne">
{% endif %}
{% endfor %}

{% endblock %}

src/posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Article - {{post.id}}</title>
{% endblock %}

{% block content %}

<h1>Le blog de Docstring</h1>

    <form method="POST">
    {% csrf_token %}

        <p>Voulez-vous vraiment supprimer: <strong>{{post|upper}}</strong>?</p>

        <input type="submit" value="Supprimer">
    </form>

{% endblock %}

src/posts/templates/posts/show.html
{% extends 'base.html' %}

{% block title %}
    <title>Article - {{post.id}}</title>
{% endblock %}

{% block content %}

<h1>Le blog de Jean-Luc</h1>

    <article class="post-detail" >
        <h2>{{post.title|upper}}</h2>
        <img src="{{post.thumbnail.url}}" alt="image ici">
        <h5>Publié par <i>{{post.author_or_default}}</i> le {{post.created_on}}</h5>
        <p>{{post.content|safe}}</p>
        <p>
            <a href="{% url 'posts:update' pk=post.id %}">Modifier</a>
            <a href="{% url 'posts:delete' pk=post.id %}">Supprimer</a>
        </p>
    </article>

{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Accueil du blog</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav>
    <a href="{% url 'posts:home' %}">Accueil</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'posts:create' %}">Ajouter un article</a>
    {% endif %}
</nav>
<section id="blog">
    {% block content %}
    {% endblock %}
</section>
</body>
</html>